name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . --file runtime/python/Dockerfile --tag cosyvoice:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: List Docker images
      run: docker images

    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ secrets.GHCR_USERNAME }} --password-stdin

    - name: Tag the Docker image for GitHub Container Registry
      run: docker tag cosyvoice:$IMAGE_TAG ghcr.io/${{ secrets.GHCR_USERNAME }}/cosyvoice:$IMAGE_TAG

    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/cosyvoice:$IMAGE_TAG
