name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(date +%s)
        docker build . --file runtime/python/Dockerfile --tag cosyvoice:$IMAGE_TAG
        echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

    - name: List Docker images
      run: docker images

    # 登录 GitHub Container Registry
    - name: Log in to GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io --username ${{ secrets.GHCR_USERNAME }} --password-stdin

    # 登录阿里云 Docker Registry
    - name: Log in to Aliyun Container Registry
      run: echo ${{ secrets.ALIYUN_DOCKER_PASSWORD }} | docker login --username ${{ secrets.ALIYUN_DOCKER_USERNAME }} registry.cn-hangzhou.aliyuncs.com --password-stdin

    # 标记镜像为 GitHub Container Registry 和 阿里云 Registry
    - name: Tag the Docker image for GitHub Container Registry
      run: |
        docker tag cosyvoice:$IMAGE_TAG ghcr.io/${{ secrets.GHCR_USERNAME }}/cosyvoice:$IMAGE_TAG
        docker tag cosyvoice:$IMAGE_TAG registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_REPO }}/cosyvoice:$IMAGE_TAG

    # 推送镜像到 GitHub Container Registry
    - name: Push the Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ secrets.GHCR_USERNAME }}/cosyvoice:$IMAGE_TAG

    # 推送镜像到阿里云镜像仓库
    - name: Push the Docker image to Aliyun Container Registry
      run: docker push registry.cn-hangzhou.aliyuncs.com/${{ secrets.ALIYUN_REPO }}/cosyvoice:$IMAGE_TAG
